# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Chee Yan Jun
# Description of the Site
description: A Year 1 Student at Nanyang Polytechnic
# URL of Image of the Site
site-image: /assets/images/welding-torch.png
# Keywords of the Site
site-keywords: Site, Personal, Polytechnic, Robotics, Coding, Programming
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://preview.redd.it/ai3w3fymdz7a1.png?width=1920&format=png&auto=webp&s=bd77fe2161ce1274163379c9ed8f8148f8869569

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: austin.chee.yj@gmail.com
facebook_username: 
twitter_username: 
instagram_username: ch__.anjun
linkedin_username: 
github_username:  nanocodex
youtube_channel_id: UCcviMWnPOh2cDINmLZjYfYg
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: nanocodex-github-io

# Name of the Author
author-name: Chee Yan Jun
# URL for the Image of the Author
author-image: /assets/images/Chee_Yan_Jun.jpg
# 60 Words About the Author
author-about: Yan Jun is a Year 1 Student at Nanyang Polytechnic in Singapore, where he is currently taking the Common ICT Programme with hopes of getting into Information Technology. He likes robots, Lego Technic, and Minecraft.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/nanocodex

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  #- jekyll-admin
  - jekyll-feed
  - github-pages

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - start.cmd
  - _posts/template-posts
  - test-page.md